name: Example CI/CD

on: 
    push:
        branches: 
            - 'cicd'
jobs:
    hello-world:
            runs-on: ubuntu-latest
            steps:
            - run: |
                pwd
                echo "Here's what you get initally"
                ls -al

            - uses: actions/checkout@v4

            - run: |
                pwd
                echo "This is what you get after a checkout"
                ls -al